### DISCUSSION TITLE
Better dev `watch` customization support

### DISCUSSION THREAD

**Discussion by stephendolan** [luckyframework/lucky#1289] [Feature requests & Ideas]
In adding translations, I realized that the dev server wasn't restarting when I changed the content in `config/locales/**/*.yml`.

In searching, I found that we hard-code the set of files that can trigger a recompile here:
https://github.com/luckyframework/lucky/blob/master/tasks/watch.cr#L212

I propose adding a new setting here that contains all of the default values in a YAML array, and allows for easier per-application customization:
https://github.com/luckyframework/lucky/blob/master/src/lucky/server_settings.cr

We'd also need to modify the generated apps to contain the default files to watch:
https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/config/watch.yml

I'm thinking the content would look something like this:

```yaml
host: 127.0.0.1
port: 5000
watch_patterns:
  - "./src/**/*.cr"
  - "./src/**/*.ecr"
  - "./config/**/*.cr"
  - "./shard.lock"
```
