### ISSUE TITLE
can't find file 'lucky_record' then LogHandler issue

### ISSUE THREAD

**Issue by wafendy** [luckyframework/lucky#725]
I'm getting this error after running the default generator `lucky init`

```
in src/dependencies.cr:1: while requiring "lucky_record": can't find file 'lucky_record'
```

After renaming all `LuckyRecord`string  to `Avram`, then I'm getting 

```
  in config/log_handler.cr:1: undefined method 'configure' for Lucky::LogHandler.class
```

Any idea how to get pass this error, all tutorials are confirming that this is the correct syntax.

**Comment by wafendy** [comment]
```
lucky (0.13.3)
Crystal 0.27.0 (2018-11-04)
```

**Comment by paulcsmith** [comment]
Are you on Linux or macOS? Is Lucky 0.13.3 from shard.lock? If so can you also paste what “lucky -v” returns? Can you also paste the “shard.yml” and “src/app.cr”?

**Comment by wafendy** [comment]
I'm on OSX v10.14.1 Mojave

```
lucky -v

gives me 'lucky_record' error
```

```
# shard.yml

name: lucky_round_three
version: 0.1.0

authors:
  - William Afendy <william.afendy@moneysmart.co>

targets:
  lucky_round_three:
    main: src/lucky_round_three.cr

crystal: 0.27.0

dependencies:
  lucky:
    github: luckyframework/lucky
    version: ~> 0.12
  authentic:
    github: luckyframework/authentic
    version: ~> 0.2
  carbon:
    github: luckyframework/carbon
    version: ~> 0.1.0

  lucky_flow:
    github: luckyframework/lucky_flow
    version: ~> 0.3
```

```
# src/app.cr

require "./dependencies"
require "./models/base_model"
require "./models/mixins/**"
require "./models/**"
require "./queries/mixins/**"
require "./queries/**"
require "./forms/mixins/**"
require "./forms/**"
require "./serializers/**"
require "./emails/base_email"
require "./emails/**"
require "./actions/mixins/**"
require "./actions/**"
require "./components/base_component"
require "./components/**"
require "./pages/**"
require "../config/env"
require "../config/**"
require "../db/migrations/**"

class App
  private getter server

  def initialize
    @server = HTTP::Server.new [
      Lucky::HttpMethodOverrideHandler.new,
      Lucky::LogHandler.new,
      Lucky::SessionHandler.new,
      Lucky::FlashHandler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::RouteHandler.new,
      Lucky::StaticFileHandler.new("./public", false),
      Lucky::RouteNotFoundHandler.new,
    ]
  end

  def base_uri
    "http://#{host}:#{port}"
  end

  def host
    Lucky::Server.settings.host
  end

  def port
    Lucky::Server.settings.port
  end

  def listen
    server.bind_tcp host, port
    server.listen
  end

  def close
    server.close
  end
end
```

**Comment by paulcsmith** [comment]
This is very odd. It looks like Lucky CLI did not install correctly. You’re using brew right? Can you try “brew upgrade” and then “brew upgrade crystal-lang lucky”

**Comment by wafendy** [comment]
Hi Paul, still no luck, `brew` says i have the latest version on both
```
wafendy@MacBook-Pro:~/playground/lucky_round_three$ brew upgrade crystal-lang lucky
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
atk                          baobab                       glooctl                      gtranslator                  pandoc-citeproc              yelp-tools

Error: crystal-lang 0.27.2 already installed
Error: luckyframework/lucky/lucky 0.13.2 already installed
```

**Comment by paulcsmith** [comment]
Can you run `which lucky` and paste the results?

Also did you first `brew uninstall crystal-lang lucky` to start totally fresh? It is definitely not generating the newest version of Lucky so this is super odd 🤔

**Comment by wafendy** [comment]
```
wafendy@MacBook-Pro:~/playground/lucky_round_three$ which lucky
/usr/local/bin/lucky
```

Let me try to `reset`,  `uninstall` then `reinstall`

**Comment by wafendy** [comment]
Hi Paul,

It's working now after full reset.

```
# shards.yml
name: lucky_round_four
version: 0.1.0

authors:
  - William Afendy <william.afendy@moneysmart.co>

targets:
  lucky_round_four:
    main: src/lucky_round_four.cr

crystal: 0.27.2

dependencies:
  lucky:
    github: luckyframework/lucky
    version: ~> 0.13
  authentic:
    github: luckyframework/authentic
    version: ~> 0.3
  carbon:
    github: luckyframework/carbon
    version: ~> 0.1
```

```
# src/app.cr

require "./dependencies"
require "./models/base_model"
require "./models/mixins/**"
require "./models/**"
require "./queries/mixins/**"
require "./queries/**"
require "./forms/mixins/**"
require "./forms/**"
require "./serializers/**"
require "./emails/base_email"
require "./emails/**"
require "./actions/mixins/**"
require "./actions/**"
require "../config/env"
require "../config/**"
require "../db/migrations/**"

class App < Lucky::BaseApp
  def middleware
    [
      Lucky::HttpMethodOverrideHandler.new,
      Lucky::LogHandler.new,

      # Disabled in API mode, but can be enabled if you need them:
      # Lucky::SessionHandler.new,
      # Lucky::FlashHandler.new,
      Lucky::ErrorHandler.new(action: Errors::Show),
      Lucky::RouteHandler.new,

      # Disabled in API mode:
      # Lucky::StaticFileHandler.new("./public", false),
      Lucky::RouteNotFoundHandler.new,
    ]
  end
end
```
