### ISSUE TITLE
Add option to customize what lucky watch watches

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/lucky#920]
In the case that you need to tell lucky to not watch certain crystal files, we should have a way to customize that.

```yml
host: 127.0.0.1
port: 5000
ignore_files:
  - src/test_*.cr 
```
